# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 166)
        Form.setMinimumSize(QtCore.QSize(400, 120))
        Form.setMaximumSize(QtCore.QSize(4000, 1200))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboreminder = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboreminder.sizePolicy().hasHeightForWidth())
        self.comboreminder.setSizePolicy(sizePolicy)
        self.comboreminder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboreminder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboreminder.setMinimumContentsLength(0)
        self.comboreminder.setObjectName("comboreminder")
        self.comboreminder.addItem("")
        self.comboreminder.addItem("")
        self.comboreminder.addItem("")
        self.comboreminder.addItem("")
        self.horizontalLayout_2.addWidget(self.comboreminder)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.comboreminder.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить человека"))
        self.label.setText(_translate("Form", "Имя:"))
        self.label_2.setText(_translate("Form", "Дата Рождения:"))
        self.label_3.setText(_translate("Form", "За сколько дней напоминать:"))
        self.comboreminder.setItemText(0, _translate("Form", "1"))
        self.comboreminder.setItemText(1, _translate("Form", "3"))
        self.comboreminder.setItemText(2, _translate("Form", "7"))
        self.comboreminder.setItemText(3, _translate("Form", "30"))
        self.btn_add.setText(_translate("Form", "Добавить"))
