# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 400)
        MainWindow.setMinimumSize(QtCore.QSize(838, 400))
        MainWindow.setMaximumSize(QtCore.QSize(838, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(155)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_addPerson = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addPerson.setObjectName("btn_addPerson")
        self.horizontalLayout.addWidget(self.btn_addPerson)
        self.btn_delPerson = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delPerson.setObjectName("btn_delPerson")
        self.horizontalLayout.addWidget(self.btn_delPerson)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkTray = QtWidgets.QCheckBox(self.centralwidget)
        self.checkTray.setChecked(False)
        self.checkTray.setObjectName("checkTray")
        self.verticalLayout.addWidget(self.checkTray)
        self.comboRemind = QtWidgets.QComboBox(self.centralwidget)
        self.comboRemind.setObjectName("comboRemind")
        self.comboRemind.addItem("")
        self.comboRemind.addItem("")
        self.comboRemind.addItem("")
        self.verticalLayout.addWidget(self.comboRemind)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Дни рождения"))
        self.label.setText(_translate("MainWindow", "Сегодня"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата Рождения"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Возраст"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дней до Д.Р."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Напоминание"))
        self.btn_addPerson.setText(_translate("MainWindow", "Добавить"))
        self.btn_delPerson.setText(_translate("MainWindow", "Удалить"))
        self.checkTray.setText(_translate("MainWindow", "Работать в фоновом режиме (с уведомлениями)"))
        self.comboRemind.setItemText(0, _translate("MainWindow", "0 - никогда"))
        self.comboRemind.setItemText(1, _translate("MainWindow", "1 - один раз в сутки"))
        self.comboRemind.setItemText(2, _translate("MainWindow", "2 - один раз в сутки и при включении"))
